apiVersion: v1
kind: Namespace
metadata:
  name: capa-events-cal
  labels:
    scenario: "17"
---
# The Sensor's pod uses this ServiceAccount to create the trigger resource (a Pod).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-sa
  namespace: capa-events-cal
  labels:
    scenario: "17"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: events-trigger
  namespace: capa-events-cal
  labels:
    scenario: "17"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-trigger
  namespace: capa-events-cal
  labels:
    scenario: "17"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: events-trigger
subjects:
  - kind: ServiceAccount
    name: events-sa
    namespace: capa-events-cal
